version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: travel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ms01qwerty
      MYSQL_DATABASE: airbnbdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Ms01qwerty
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: travel-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:Ms01qwerty@localhost:3306/airbnbdb
      SECRET_KEY: your-secret-key
    restart: always

volumes:
  mysql_data:
